### ISSUE TITLE
Add treatment

### ISSUE THREAD

**Issue by rozeggo** [epiverse-trace/epidemics#42]
The model should be able to alter the probability of hospitalisation/becoming a case

**Comment by adamkucharski** [comment]
Does the current functionality also allow hospitalisation to act as isolation (as it does for Ebola etc)? Conceptually its obviously easier to have a burden model that doesn't effect dynamics (because just taking case numbers and scaling as a post-processing step) as a starting point. If there is an effect on transmission, remember it was in some cases easier to split out case/not case earlier on for bookkeeping purposes e.g. below from [Ebola analysis](https://www.pnas.org/doi/10.1073/pnas.1508814112) – this may already been on radar, but happy to share past decision struggles if not! (Or ignore if not priority for now)

<img width="503" alt="ebola" src="https://github.com/epiverse-trace/epidemics/assets/8329046/92599ef7-9854-4efa-8c2b-669cabaa2c0e">

**Comment by pratikunterwegs** [comment]
Will add better explanation of new `<rate_interventions>` in PR #91 which implements them.
